//! macOS secret clipboard implementation.
//!
//! `CurrentHostOnly` keeps the item out of Universal Clipboard. The custom
//! pasteboard types are conventions honoured by password managers and common
//! clipboard-history tools; they are advisory, not an OS access-control
//! boundary. Calls should originate on the GPUI/main thread.

use objc2::{rc::Retained, runtime::ProtocolObject};
use objc2_app_kit::{
    NSPasteboard, NSPasteboardContentsOptions, NSPasteboardItem, NSPasteboardWriting,
};
use objc2_foundation::{NSArray, NSString};

use super::{ClipboardChangeCount, ClipboardError, ClipboardResult};

const STRING_TYPE: &str = "public.utf8-plain-text";
const CONCEALED_TYPE: &str = "org.nspasteboard.ConcealedType";
const TRANSIENT_TYPE: &str = "org.nspasteboard.TransientType";
const AUTO_GENERATED_TYPE: &str = "org.nspasteboard.AutoGeneratedType";

/// Write a secret to the general pasteboard and return its generation.
///
/// No copy of `text` is kept by this module after AppKit accepts the item.
/// The pasteboard item is restricted to this Mac and carries the concealed,
/// transient, and auto-generated hints used by clipboard-history tools.
pub fn write_secret_text(text: &str) -> ClipboardResult<ClipboardChangeCount> {
    write_secret_to(&NSPasteboard::generalPasteboard(), text)
}

/// Clear the general pasteboard only if it still contains the generation
/// returned by [`write_secret_text`]. Returns `false` when another process or
/// the user has changed the clipboard in the meantime.
///
/// AppKit has no atomic compare-and-clear operation, so this is the strongest
/// check its change-count API provides.
pub fn clear_if_unchanged(expected: ClipboardChangeCount) -> ClipboardResult<bool> {
    Ok(clear_if_unchanged_on(
        &NSPasteboard::generalPasteboard(),
        expected,
    ))
}

fn write_secret_to(pasteboard: &NSPasteboard, text: &str) -> ClipboardResult<ClipboardChangeCount> {
    // Build the complete item before touching the pasteboard. This avoids a
    // window where a history manager could observe the string type before the
    // concealed/transient markers have been attached.
    let item = NSPasteboardItem::new();
    let value = NSString::from_str(text);
    let empty = NSString::from_str("");
    let types = [
        (STRING_TYPE, value.as_ref()),
        (CONCEALED_TYPE, empty.as_ref()),
        (TRANSIENT_TYPE, empty.as_ref()),
        (AUTO_GENERATED_TYPE, empty.as_ref()),
    ];

    for (type_name, value) in types {
        let pasteboard_type = NSString::from_str(type_name);
        if !item.setString_forType(value, &pasteboard_type) {
            return Err(ClipboardError::ItemConstructionFailed);
        }
    }

    let item: Retained<ProtocolObject<dyn NSPasteboardWriting>> =
        ProtocolObject::from_retained(item);
    let objects = NSArray::from_retained_slice(&[item]);

    let prepared_count = ClipboardChangeCount::from_raw(
        pasteboard.prepareForNewContentsWithOptions(NSPasteboardContentsOptions::CurrentHostOnly),
    );
    if !pasteboard.writeObjects(&objects) {
        // Only clear the empty/partial generation we prepared. If another app
        // has already replaced it, leave that newer clipboard untouched.
        let _ = clear_if_unchanged_on(pasteboard, prepared_count);
        return Err(ClipboardError::WriteFailed);
    }

    Ok(ClipboardChangeCount::from_raw(pasteboard.changeCount()))
}

fn clear_if_unchanged_on(pasteboard: &NSPasteboard, expected: ClipboardChangeCount) -> bool {
    if pasteboard.changeCount() != expected.into_raw() {
        return false;
    }

    pasteboard.clearContents();
    true
}

#[cfg(test)]
mod tests {
    use super::*;

    fn text_for_type(pasteboard: &NSPasteboard, type_name: &str) -> Option<String> {
        let pasteboard_type = NSString::from_str(type_name);
        pasteboard
            .stringForType(&pasteboard_type)
            .map(|value| value.to_string())
    }

    #[test]
    fn secret_item_has_all_privacy_types() {
        let pasteboard = NSPasteboard::pasteboardWithUniqueName();
        let token = write_secret_to(&pasteboard, "test-secret").expect("write secret");

        assert_eq!(
            text_for_type(&pasteboard, STRING_TYPE).as_deref(),
            Some("test-secret")
        );
        assert_eq!(
            text_for_type(&pasteboard, CONCEALED_TYPE).as_deref(),
            Some("")
        );
        assert_eq!(
            text_for_type(&pasteboard, TRANSIENT_TYPE).as_deref(),
            Some("")
        );
        assert_eq!(
            text_for_type(&pasteboard, AUTO_GENERATED_TYPE).as_deref(),
            Some("")
        );
        assert_eq!(pasteboard.changeCount(), token.into_raw());
    }

    #[test]
    fn delayed_clear_does_not_erase_newer_clipboard_contents() {
        let pasteboard = NSPasteboard::pasteboardWithUniqueName();
        let stale = write_secret_to(&pasteboard, "first").expect("write first");
        let current = write_secret_to(&pasteboard, "second").expect("write second");

        assert!(!clear_if_unchanged_on(&pasteboard, stale));
        assert_eq!(
            text_for_type(&pasteboard, STRING_TYPE).as_deref(),
            Some("second")
        );

        assert!(clear_if_unchanged_on(&pasteboard, current));
        assert_eq!(text_for_type(&pasteboard, STRING_TYPE), None);
    }
}
